# 1500 prize bond list 2022

In [38]:
import numpy as np
import pandas as pd 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [50]:
bond_1500 = pd.read_csv("1500_prize_bond_list_2022.csv",sep='	')
bond_1500[["c","d","e","f","g","h"]] = bond_1500[["c","d","e","f","g","h"]].replace(np.nan,0)
bond_1500.loc[:,['a','b','c','d','e','f','g','h']] = bond_1500.loc[:,['a','b','c','d','e','f','g','h']].apply(pd.to_numeric).astype('int64')
bond_number = int(input("Please Enter The Bond Number: "))
bond_1500_numbers = np.array(bond_1500)
for i in bond_1500_numbers:
    for j in i:
        if j == bond_number:
            print('You Win A Prize With Bond Number :',bond_number)
        break
        else:
            print('soory')
        break

SyntaxError: invalid syntax (<ipython-input-50-25a21d348675>, line 11)

In [ ]:
bond_1500 = pd.read_csv("1500_prize_bond_list_2022.csv",sep='	')
bond_1500[["c","d","e","f","g","h"]] = bond_1500[["c","d","e","f","g","h"]].replace(np.nan,0)
bond_1500.loc[:,['a','b','c','d','e','f','g','h']] = bond_1500.loc[:,['a','b','c','d','e','f','g','h']].apply(pd.to_numeric).astype('int64')
bond_number = int(input("Please Enter The Bond Number: "))
bond_1500_numbers = np.array(bond_1500)
for i in bond_1500_numbers:
    for j in i:
        if j == bond_number:
            print('You Win A Prize With Bond Number :',bond_number)
            break
        else:
            print('soory')
        break

In [49]:
bond_1500 = pd.read_csv("1500_prize_bond_list_2022.csv",sep='	')
bond_1500[["c","d","e","f","g","h"]] = bond_1500[["c","d","e","f","g","h"]].replace(np.nan,0)
bond_1500.loc[:,['a','b','c','d','e','f','g','h']] = bond_1500.loc[:,['a','b','c','d','e','f','g','h']].apply(pd.to_numeric).astype('int64')
number_list = []
#bond_number = int(input("Please Enter The Bond Number: "))
bond_1500_numbers = np.array(bond_1500)
number_list.append(bond_1500_numbers)
for i in number_list:
    for j in i:
        print(j)

[1459 1817 2289 3008 3350 5009 5551 5584]
[ 7033  7499  8062  8150  8589  8639 10076 10139]
[10992 12794 13561 14217 15178 15469 15534 16214]
[17289 17439 18723 19652 20539 21623 21689 22458]
[23157 23330 23447 24755 24817 25107 25609 26432]
[26531 27400 27938 28211 29231 29323 29357 30079]
[30617 30665 30842 31962 32322 32637 32745 33992]
[34253 34638 34766 35113 35284 35453 35504 35618]
[35733 35914 37728 37733 37751 38218 38427 39109]
[41179 41231 42281 43138 44332 44348 45240 46362]
[47660 48872 49088 49406 50444 51152 51323 52392]
[53659 53934 55051 55310 55628 56559 56916 57090]
[57636 58225 58450 59068 59273 59905 60214 60228]
[62124 62328 63299 63541 64062 64326 64487 64782]
[64891 65824 66192 66225 68136 68950 69569 69621]
[69883 71200 72008 72046 72347 72723 73072 73318]
[73763 74468 75942 76475 76679 77730 79122 81246]
[81589 81741 82502 83217 83399 83467 83510 84162]
[84737 85099 85920 87502 87869 88238 90189 90414]
[92108 92199 93625 94219 96179 96866 97428 97823]
[ 97897 

In [6]:
import numpy as np
power_level_list = np.array([1000,4000,150,9001,1500])
any(power_level_list > 9000) # anyone is true then result is true

True

In [7]:
import numpy as np
power_level_list = np.array([1000,4000,150,9001,1500])


In [10]:
bond_1500 = pd.read_csv("1500_prize_bond_list_2022.csv",sep='	')
bond_1500_df_num = np.array(bond_1500)
#bond_1500_df_num
number = int(input("enter a number: "))
for i in bond_1500_df_num:
    if number == i:
        print('conraglutions',i)
#any(bond_1500_df_num==number)
#print('hi')

enter a number: 2


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [7]:
bond_1500 = pd.read_csv("1500_prize_bond_list_2022.csv",sep='	')
bond_1500_df = np.array(bond_1500)
bond_1500_df = pd.DataFrame(bond_1500)
bond_1500_df[["c","d","e","f","g","h"]] = bond_1500_df[["c","d","e","f","g","h"]].replace(np.nan,0)
bond_1500_df.loc[:,'a':'b'] = bond_1500_df.loc[:,'a':'b'].apply(pd.to_numeric).astype('int64')
bond_1500_df.columns

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], dtype='object')

In [28]:
bond_1500 = pd.read_csv("1500_prize_bond_list_2022.csv",sep='	')
bond_1500_df = pd.DataFrame(bond_1500)
bond_1500_df[["c","d","e","f","g","h"]] = bond_1500_df[["c","d","e","f","g","h"]].replace(np.nan,0)
bond_1500_df.loc[:,['a','b','c','d','e','f','g','h']] = bond_1500_df.loc[:,['a','b','c','d','e','f','g','h']].apply(pd.to_numeric).astype('int64')
all(bond_1500_df.values)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
bond_1500 = pd.read_csv("1500_prize_bond_list_2022.csv",sep='	')
bond_1500_df = pd.DataFrame(bond_1500)
bond_1500_df[["c","d","e","f","g","h"]] = bond_1500_df[["c","d","e","f","g","h"]].replace(np.nan,0)
bond_1500_df.loc[:,['a','b','c','d','e','f','g','h']] = bond_1500_df.loc[:,['a','b','c','d','e','f','g','h']].apply(pd.to_numeric).astype('int64')
all(bond_1500_df.values)
bond_1500_df_input = int(input('please enter a number: '))
for a in bond_1500_df.values:
    if a == bond_1500_df_input:
        print('hi',bond_1500_df_input.all())


In [17]:
bond_1500

a       b         c         d         e         f         g  \
0      1459    1817    2289.0    3008.0    3350.0    5009.0    5551.0   
1      7033    7499    8062.0    8150.0    8589.0    8639.0   10076.0   
2     10992   12794   13561.0   14217.0   15178.0   15469.0   15534.0   
3     17289   17439   18723.0   19652.0   20539.0   21623.0   21689.0   
4     23157   23330   23447.0   24755.0   24817.0   25107.0   25609.0   
..      ...     ...       ...       ...       ...       ...       ...   
207  974318  974488  974761.0  975108.0  977101.0  977930.0  979434.0   
208  982152  983530  983657.0  984678.0  986202.0  987447.0  988209.0   
209  988468  988630  991747.0  992216.0  992829.0  992919.0  993466.0   
210  993927  994086  995206.0  996513.0  996645.0  996669.0  996677.0   
211  998468  998819       0.0       0.0       0.0       0.0       0.0   

            h  
0      5584.0  
1     10139.0  
2     16214.0  
3     22458.0  
4     26432.0  
..        ...  
207  981269.0  
208  988235.0  
209  993607.0  
210  997640.0  
211       0.0  

[212 rows x 8 columns]

In [10]:
bond_1500 = pd.read_csv("1500_prize_bond_list_2022.csv",sep='	')
enter_number = int(input("please enter number: "))
if enter_number == bond_1500[bond_1500['a']]:
    print("hi ",enter_number)
else:
    print('sorry')

please enter number: 12334


ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [11]:
search_number = bond_1500[(bond_1500['a'] == enter_number)]
print('hi')

hi


In [ ]:
data_query = data[(data['year'] >= 2005) & (data['year'] <= 2010)]

In [32]:
ls = [i for i in range(100) if i%3 == 0]
print(ls)

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]
