# The NumPy ndarray: A Multidimensional Array Object

In [2]:
import numpy as np
from random import randrange

One of the key features of NumPy is its N-dimensional array object, or ndarray, which
is a fast, flexible container for large data sets in Python. Arrays enable you to perform
mathematical operations on whole blocks of data using similar syntax to the equivalent
operations between scalar elements:

In [2]:
data = np.random.randn(2,3)
data

array([[-0.16209354, -0.27077638,  1.24978007],
       [ 0.02563852, -0.4232243 ,  1.6211361 ]])

In [3]:
data * 10

array([[-1.62093538, -2.70776381, 12.49780074],
       [ 0.25638521, -4.23224305, 16.21136098]])

In [4]:
data + data

array([[-0.32418708, -0.54155276,  2.49956015],
       [ 0.05127704, -0.84644861,  3.2422722 ]])

In [5]:
data.shape

(2, 3)

In [6]:
data.dtype


dtype('float64')

# Creating ndarrays

The easiest way to create an array is to use the array function. This accepts any sequence-
like object (including other arrays) and produces a new NumPy array containing
the passed data. For example, a list is a good candidate for conversion:

In [7]:
data1 = [6, 7.5, 8, 0, 1]

In [8]:
arr = np.array(data1)
arr

array([6. , 7.5, 8. , 0. , 1. ])

Nested sequences, like a list of equal-length lists, will be converted into a multidimensional
array:

In [9]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [10]:
arr1=np.array(data2)
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr1.ndim


2

In [12]:
arr1.shape

(2, 4)

In [13]:
arr1.dtype

dtype('int32')

In addition to np.array, there are a number of other functions for creating new arrays.
As examples, zeros and ones create arrays of 0’s or 1’s, respectively, with a given length
or shape. empty creates an array without initializing its values to any particular value.
To create a higher dimensional array with these methods, pass a tuple for the shape:

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

It’s not safe to assume that np.empty will return an array of all zeros. In
many cases, as previously shown, it will return uninitialized garbage
values.

In [6]:
a = np.arange(15)
number = int(input("enter a number: "))
for i in a:
    if i == number:
        print("conragluation ",i)

enter a number: 12
conragluation  12


Table 4-1. Array creation functions

Function Description


array Convert input data (list, tuple, array, or other sequence type) to an ndarray either by
inferring a dtype or explicitly specifying a dtype. Copies the input data by default.
asarray Convert input to ndarray, but do not copy if the input is already an ndarray
arange Like the built-in range but returns an ndarray instead of a list.
ones, ones_like Produce an array of all 1’s with the given shape and dtype. ones_like takes another
array and produces a ones array of the same shape and dtype.
zeros, zeros_like Like ones and ones_like but producing arrays of 0’s instead
empty, empty_like Create new arrays by allocating new memory, but do not populate with any values like
ones and zeros
eye, identity Create a square N x N identity matrix (1’s on the diagonal and 0’s elsewhere)

# Data Types for ndarrays

The data type or dtype is a special object containing the information the ndarray needs
to interpret a chunk of memory as a particular type of data:

In [18]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [19]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2

array([1, 2, 3])

Dtypes are part of what make NumPy so powerful and flexible. In most cases they map
directly onto an underlying machine representation, which makes it easy to read and
write binary streams of data to disk and also to connect to code written in a low-level
language like C or Fortran. The numerical dtypes are named the same way: a type name,
like float or int, followed by a number indicating the number of bits per element. A
standard double-precision floating point value (what’s used under the hood in Python’s
float object) takes up 8 bytes or 64 bits. Thus, this type is known in NumPy as
float64. See Table 4-2 for a full listing of NumPy’s supported data types.

Don’t worry about memorizing the NumPy dtypes, especially if you’re
a new user. It’s often only necessary to care about the general kind of
data you’re dealing with, whether floating point, complex, integer,
boolean, string, or general Python object. When you need more control
over how data are stored in memory and on disk, especially large data
sets, it is good to know that you have control over the storage type.

Table 4-2. NumPy data types

Type Type Code Description

int8, uint8 i1, u1 Signed and unsigned 8-bit (1 byte) integer types
int16, uint16 i2, u2 Signed and unsigned 16-bit integer types
int32, uint32 i4, u4 Signed and unsigned 32-bit integer types
int64, uint64 i8, u8 Signed and unsigned 32-bit integer types
float16 f2 Half-precision floating point
float32 f4 or f Standard single-precision floating point. Compatible with C float
float64, float128 f8 or d Standard double-precision floating point. Compatible with C double
and Python float object
float128 f16 or g Extended-precision floating point
complex64, complex128,
complex256
c8, c16,
c32
Complex numbers represented by two 32, 64, or 128 floats, respectively
bool ? Boolean type storing True and False values
object O Python object type
string_ S Fixed-length string type (1 byte per character). For example, to create
a string dtype with length 10, use 'S10'.
unicode_ U Fixed-length unicode type (number of bytes platform specific). Same
specification semantics as string_ (e.g. 'U10').

You can explicitly convert or cast an array from one dtype to another using ndarray’s
astype method:

In [20]:
arr = np.array([1, 2, 3, 4, 5])

In [22]:
arr.dtype

dtype('int32')

In [23]:
float_arr = arr.astype(np.float64)

In [26]:
float_arr.dtype

dtype('float64')

In this example, integers were cast to floating point. If I cast some floating point numbers
to be of integer dtype, the decimal part will be truncated:

In [27]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [30]:
arr.astype(np.int64)

array([ 3, -1, -2,  0, 12, 10], dtype=int64)

Should you have an array of strings representing numbers, you can use astype to convert
them to numeric form:

In [31]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [38]:
#numeric_strings.astype(int)

In [39]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [40]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [42]:
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [44]:
calibers.astype(calibers.dtype)

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [ ]:
int_array.astype(calibers.dtype)

In [46]:
empty_uint32 = np.empty(8, dtype='u4')

In [47]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

Calling astype always creates a new array (a copy of the data), even if
the new dtype is the same as the old dtype.

It’s worth keeping in mind that floating point numbers, such as those
in float64 and float32 arrays, are only capable of approximating fractional
quantities. In complex computations, you may accrue some
floating point error, making comparisons only valid up to a certain number
of decimal places.

# Operations between Arrays and Scalars

Arrays are important because they enable you to express batch operations on data
without writing any for loops. This is usually called vectorization. Any arithmetic operations
between equal-size arrays applies the operation elementwise:

In [48]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [49]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [50]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [51]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [54]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [58]:
arr%2

array([[1., 0., 1.],
       [0., 1., 0.]])

Operations between differently sized arrays is called broadcasting and will be discussed
in more detail in Chapter 12. Having a deep understanding of broadcasting is not necessary
for most of this book.